### ISSUE TITLE
Add desktop and appdata files

### ISSUE THREAD

**Issue by City-busz** [rzvncj/xCHM#1]
I'm maintaining desktop and appdata files for packaging on Arch Linux:
https://git.archlinux.org/svntogit/community.git/tree/trunk/xchm.desktop?h=packages/xchm
https://git.archlinux.org/svntogit/community.git/tree/trunk/xchm.appdata.xml?h=packages/xchm

It would be nice to include these files in the upstream code, so other distributions could also use the same files.

**Comment by rzvncj** [comment]
Include them where? In the root directory?
Also, could you please remove all links to Sourceforge / replace them with links to GitHub where applicable?

**Comment by City-busz** [comment]
Projects usually include these files in a `data` folder together with icons and other data files.

The files should be installed during `make install` into the following locations:
`/usr/share/applications/xchm.desktop`
`/usr/share/metainfo/xchm.appdata.xml`

The updated appdata file:
```
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>com.github.xchm</id>
  <launchable type="desktop-id">xchm.desktop</launchable>
  <name>xCHM</name>
  <summary>View CHM files</summary>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>GPL-2.0</project_license>
  <description>
    <p>xCHM is a viewer for Compiled HTML Help (CHM) files. It can show the contents tree if one is available, print the current page and do the usual history stunts. It allows one to change fonts and search for text in all the pages of the file, or in the page's titles.</p>
  </description>
  <screenshots>
    <screenshot type="default">
      <image>https://raw.githubusercontent.com/rzvncj/xCHM/master/art/screenshot.png</image>
    </screenshot>
  </screenshots>
  <url type="homepage">https://github.com/rzvncj/xCHM</url>
</component>
```

**Comment by rzvncj** [comment]
I've added the files to the repo for now: https://github.com/rzvncj/xCHM/commit/bb1ef4646f07e3c5208802c096cfa31b0a5b763f
I'll see about installing them automatically a bit later.

**Comment by rzvncj** [comment]
It's done. Please pull master and see if it does what you want.

**Comment by rzvncj** [comment]
While I'm at adding external files, I've added the Debian man page as well.

**Comment by rzvncj** [comment]
Here's the release: https://github.com/rzvncj/xCHM/releases/tag/1.29

**Comment by City-busz** [comment]
It works. Thanks!

One more think is needed. Currently all icons are installed under `/usr/share/pixmaps/xchm-*.png`. But the desktop file what I proposed expects an icon called `xchm.png`.

I think the best would be to put the icons under the "hicolor" directory instead of "pixmaps" by following the [Icon Theme Specification](https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout):
```
art/xchm-16.png -> /usr/share/icons/hicolor/16x16/apps/xchm.png
art/xchm-32.png -> /usr/share/icons/hicolor/32x32/apps/xchm.png
art/xchm-48.png -> /usr/share/icons/hicolor/48x48/apps/xchm.png
art/xchm-128.png -> /usr/share/icons/hicolor/128x128/apps/xchm.png
```

**Comment by rzvncj** [comment]
https://github.com/rzvncj/xCHM/releases/tag/1.30

**Comment by City-busz** [comment]
Thanks!
