### ISSUE TITLE
xCHM don’t show some pages

### ISSUE THREAD

**Issue by ghost** [rzvncj/xCHM#19]
Some pages are opened empty.

For example: documentation for Advantech DAQNavi Driver for Linux
[https://advdownload.advantech.com/productfile/Downloadfile1/1-1TAGQL6/Document.zip](https://advdownload.advantech.com/productfile/Downloadfile1/1-1TAGQL6/Document.zip) 
In DAQNavi_User_Interface_ForLinux.chm file page “PCI” can’t be opened (and many others pages), however on windows everything is ok.

**Comment by rzvncj** [comment]
If you mean "PCI Series", it doesn't have an URL entry in the .hhc file inside the CHM (renamed to .txt so Github allows me to upload it, and attached here). xCHM is unfortunately a best-effort UNIX solution working with an undocumented Microsoft format, so supporting every feature the native Windows viewer supports is not a goal for the project.

[DAQNavi_User_Interface_ForLinux.txt](https://github.com/rzvncj/xCHM/files/6430282/DAQNavi_User_Interface_ForLinux.txt)
