### ISSUE TITLE
quite a few tile blocks instead of readable characters - it's distracting

### ISSUE THREAD

**Issue by ozar** [rzvncj/xCHM#2]
good day, rzvncj - hope all is well.

I'm getting quite a few tile blocks instead of readable characters with some files (using serif font) is there a way to get around that?  I tried a number of different fonts, but no luck.  Is it a UTF-8 thing, by chance?

Thanks for your continued work on this project.  It's the best chm reader available for Linux users, in my opinion.

**Comment by ozar** [comment]
oops, forgot to say I'm running Arch and version 1.28 of xchm

**Comment by rzvncj** [comment]
It's hard to say without the .chm file or at least a screenshot. As far as I know, the proper fonts should fix your problem, but the .chm may be malformed.

The easiest way to tell is to simply unpack the .chm file (it's basically an archive of HTML files), and open the file in question in an actual browser. You should be able to extract the .chm file with `extract_chmLib`, from the `chmlib` package.

**Comment by ozar** [comment]
Good day, and thanks for replying, rzvncj!

I did extract the chm file a few days before reporting the problem here, and it looked fine in Firefox.  It seems to be few different symbols like extra-long dashes and copyright symbols that are throwing xchm off-track.  I was using a serif font like the chm file designated but those symbols didn't display correctly and the dashes were used quite a bit throughout the file.  I'll try some other chm files to check for issues there.  Thanks again for your time and work on xchm.

**Comment by rzvncj** [comment]
No problem. You can attach your .chm file here, or upload it somewhere and leave the link if possible. Maybe then we can then figure out what the problem is in your case.

**Comment by ozar** [comment]
Sorry it took me a while to get back to you.  It's the file itself.  I looked at a number of chm files and books and no problems with any of them.  I'll close this since it isn't an issue with xchm.  Thanks for your patience and for xchm.

**Comment by rzvncj** [comment]
No problem. Thanks for the report.
