### ISSUE TITLE
Please keep settings in XDG_CONFIG_HOME/xchm/ directory

### ISSUE THREAD

**Issue by marksvc** [rzvncj/xCHM#20]
Thank you for your work on xCHM. It appears that xCHM is writing to a configuration file at `$HOME/.xchm`. To avoid cluttering `$HOME/` with lots of dot-files for various applications, a [specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) has been made to define a standard place to store these. Could xCHM be changed to use this different location? I suggest `$XDG_CONFIG_HOME/xchm/settings.ini` or `$XDG_CONFIG_HOME/xchm/config.ini`.

You can see more information about this at https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

We use xCHM to display help files for some cross-platform software. When bundling xCHM with the software in a [Flatpak](https://www.flatpak.org/) package, I found that because xCHM writes to `$HOME/.xchm` and even `$HOME/.xchmXXXXXX`, where` XXXXXX` are random characters (eg `.xchm7R9qbG` or `.xchmfIaTpL`), I needed to request for the flatpak application to have write access to the entire `$HOME` directory or xCHM would give errors. If xCHM only writes configuration files to the `$XDG_CONFIG_HOME/xchm` directory, I would just need to request permission for xCHM to write to `$XDG_CONFIG_HOME/xchm` -- much less significant than granting read-write access to the whole home directory.

When `XDG_CONFIG_HOME` is not set, a application can fall back to using the standard location of `$HOME/.config`.

**Comment by rzvncj** [comment]
Thanks, happy to see xCHM still being useful. Could you compile and test the `XDG_config` branch I've just pushed? Assuming you're compiling against wxWidgets >= 3.1.1 it should do what you want it to.

**Comment by marksvc** [comment]
Thank you! I had tried modifying xchm to make it write to a different config directory and wasn't successful, but I see that I had gone about it quite a different way. Thank you for your fix.

I have tested using wxWidgets v3.1.5, and xchm branch XDG_config. 

I observed that xchm produced no errors about not being able to write to a config file when it wouldn't have been able to write to HOME. I observe that a file appeared at `XDG_CONFIG_HOME/xchm.conf`.

I unfortunately also found that xchm is no longer _rendering_ the chm html, but is instead displaying the raw html :-). I see that it renders the HTML with wxWidgets 3.0.5.1 but not with 3.1.0, so I'll need to check on why it's not working with wxWidgets 3.1.0+.

But I don't suppose the HTML rendering problem is related to this issue or the fix. I think branch XDG_config solves the config file location issue, and will allow me to bundle xchm without asking for read and write permission to the entire HOME. Thanks!

**Comment by rzvncj** [comment]
Thanks for checking. I've merged the XDG support branch into master, and the change will be available with the next release.

No, I don't see how this change could possibly affect HTML rendering. FWIW, rendering works fine with the custom wxWidgets 3.1.5 build I've linked for testing:

![Screenshot from 2021-11-19 23-03-46](https://user-images.githubusercontent.com/36885180/142691443-3f1b6218-8d44-4df7-b9d5-969cbc083bda.png)

If there's an actual bug that you can reproduce, feel free to open up another issue and I'll take a look.
