### ISSUE TITLE
PO files generation

### ISSUE THREAD

**Issue by kartikm** [rzvncj/xCHM#31]
Once xCHM is built, it updates the timestamp of PO files, this seems to be causing a bug reported at Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1047187

Can you edit Makefile (or related fixes) to avoid this?

**Comment by rzvncj** [comment]
First, I'd like to understand the problem.

AFAICT, it says "binary file contents changed" so it doesn't look to me like the timestamp alone is what bothers them. Are you sure it's just the date that's changing?

The .po generation is being done automatically by the autotools build system. The relevant parts are `SUBDIRS = m4 po src art mac data man` in Makefile.am, and the LINGUAS and POTFILES.in files in the po/ directory. I don't control that behaviour.

**Comment by rzvncj** [comment]
No updates in over an year, closing this.
