### ISSUE TITLE
Left pane has small font

### ISSUE THREAD

**Issue by LightningStalker** [rzvncj/xCHM#36]
I change font size but left pane still default.

**Comment by rzvncj** [comment]
That's not a bug. It works as intended.

To change the size of menu fonts, or other standard widgets fonts, you need to change your system's font sizes (possibly from the accessibility settings).

**Comment by LightningStalker** [comment]
No change to left pane, everything else bigger

**Comment by rzvncj** [comment]
Yes, I do understand your issue.

But the left pane is part of the window interface, like the menu text and the text on the buttons. It is _not_ part of the displayed HTML page.

To think of another example, if you open the bookmarks list in Firefox and then zoom in a displayed page, the text in the bookmarks list does not get bigger.

So again, this is not a bug.

Depending on your window manager, you might be able to increase the size of the fonts for all windows by changing your accessibility settings.
