### ISSUE TITLE
specify topic on command line?

### ISSUE THREAD

**Issue by StephenMcConnel** [rzvncj/xCHM#4]
Is it possible to specify the topic as well as the help file on the command line?  I can't see any way to do that and a program I work on needs that functionality.  We have been using chmsee for years, but that's no longer viable at all.  xchm looks like it would work well, but always opening to the first page of the file doesn't really work for our user base.

**Comment by rzvncj** [comment]
There's this:
```
$ xchm --help
Usage: xchm [-c <num>] [-t] [-i] [-h] [file]
  -c, --contextid=<num>	context-Id to open in file, requires that a file be specified
  -t, --notopics       	don't load the topics tree
  -i, --noindex        	don't load the index
  -h, --help           	displays this message.
```
if you know your contextid. And you can always use the special virtual filesystem syntax that xCHM uses internally:
```
xchm file:jdk150.chm#xchm:/jdk150/api/java/applet/package-summary.html
```
So, yes, I'd say what you're after is already perfectly possible.

**Comment by StephenMcConnel** [comment]
Thanks.  The information about the "special virtual filesystem syntax" was exactly what I needed to get my program's context sensitive help working.  (I don't know anything about the context ids, and the code is full of references to topic locations in the path notation.)  It might be helpful to others to document the special syntax in the --help output.

**Comment by rzvncj** [comment]
http://resources.esri.com/help/9.3/arcgisdesktop/com/gp_toolref/documenting_tools_and_toolboxes/referencing_a_compiled_help_file.htm

**Comment by rzvncj** [comment]
https://sourceforge.net/p/xchm/mailman/xchm-general/thread/413DB8CE.30504@gmx.net/

**Comment by rzvncj** [comment]
Context IDs are really the proper way to go about this. The special syntax might change in the future.
