### ISSUE TITLE
When moving to next page, show the top of the page

### ISSUE THREAD

**Issue by xihh87** [rzvncj/xCHM#7]
While I'm pleased with the software overall, when reading documentation that contains multiple long pages I need to use a shortcut to go to the top on every page. This is annoying and usability would be improved a lot but fixing this issue.

I'm using xchm 1.23 as packaged on debian 10 for i386.

**Comment by rzvncj** [comment]
I don't understand your scenario. What are you doing (exactly), what's happening and what would you like to happen instead?

Also, this is free software under the GPL - pull requests from users who fix their own problems are welcome.

**Comment by rzvncj** [comment]
Right, I've figured out why I don't understand your issue: it's been fixed quite a while ago, but you're using an ancient version on Debian.
Closing this as there's nothing more I can do.
