### ISSUE TITLE
Add view option to hide tools

### ISSUE THREAD

**Issue by xihh87** [rzvncj/xCHM#8]
It would be nice if this tool could be hidden to make the best of screen realstate.

A logical place to search for this option is in the view menu.

![2019-11-06-193947](https://user-images.githubusercontent.com/16003955/68353112-2e673480-00ce-11ea-925a-a91b96e17f6d.png)

**Comment by rzvncj** [comment]
That's probably doable at some point. Until then, you can make the most of your screen real estate by clicking on the "Fullscreen" button.

**Comment by rzvncj** [comment]
It's done on the `master` branch. The next release (1.31) will have this in whenever it happens - in the meantime you can just compile your own from source if you need it sooner.
