### ISSUE TITLE
Crash when searching specific file, or no search results.

### ISSUE THREAD

**Issue by bernhardu** [rzvncj/xCHM#9]
In Debian this bug [report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944284) got created.
I think this affects upstream too.
Viewing old versions of the php chm files makes xchm crash.
Newer versions do not crash but do not show any search results.
Could you reproduce the issue with the files linked there?
And makes the patch attached there sense to you?

**Comment by rzvncj** [comment]
https://github.com/rzvncj/xCHM/releases/tag/1.31

Thanks for the report.

**Comment by kartikm** [comment]
Thanks @rzvncj
